### PR TITLE
Added zh_cn.json for Simplified Chinese

### PR DESCRIPTION
**Pull request by Pairman**
Added zh_cn.json for Simplified Chinese language. I'm not a specialist at doing translations and I've barely used worldedits, therefore I completed this translation file under the help of many documents about worldedit commands. The translation style is not too consistent with the en_us.json. I've tried my best.

### CODE REVIEW

**Comment by Ghoulboy78** [comment]
Well to be honest it's not like we have anyone who speaks any Chinese on the main dev team, so idk what to do with this. (to the developers) should we approve this, or ask someone who speaks Chinese to come review?

**Comment by altrisi** [comment]
I think as long as everything appears translated and works (not throwing errors on placeholders) we should trust them. If it was just some random easy form or something like that it would be less trustable, but making a PR is not as easy as that.

Plus some of the systems using many translations (mainly help menu) are really in need of upgrading (in my TO-DO list), but hopefully it shouldn't affect this (here meaning that it would be difficult for machines to make acceptable translations of some strings).

Just to be sure I don't break things in my translations v2.1 update: There's no problem if at some point we remove the `_cn` suffix and just keep it as `zh`, right? (will be changed when I get to finish #88) 

Thanks! Will review things don't throw Soon™

**Comment by Pairman** [comment]
> I think as long as everything appears translated and works (not throwing errors on placeholders) we should trust them. If it was just some random easy form or something like that it would be less trustable, but making a PR is not as easy as that.
> 
> Plus some of the systems using many translations (mainly help menu) are really in need of upgrading (in my TO-DO list), but hopefully it shouldn't affect this (here meaning that it would be difficult for machines to make acceptable translations of some strings).
> 
> Just to be sure I don't break things in my translations v2.1 update: There's no problem if at some point we remove the `_cn` suffix and just keep it as `zh`, right? (will be changed when I get to finish #88) 
> 
> Thanks! Will review things don't throw Soon™

Feel free to change the filename

**Review by altrisi — APPROVED** [review]
I'm approving this, not sure why I didn't before.

Thanks for contributing!

**Review by Firigion — APPROVED** [review]
not that I can read chinese anyway. Thanks!

**Pull request merged**
